<div class="panel panel-default">
	<div class="panel-body">
	<h3>About this guide</h3>
	<p><img src="assets/happy-hours-logo.jpg" style="width:33.3%; margin-left:20px;" class="pull-right">Use our guide to find the best happy hour specials and deals at Austin bars and restaurants. It’s not just drinks you can get on the cheap - many restaurants offer half-priced food menus. The Austin happy hour guide can be accessed on your desktop computer or your mobile phone at any time by directing your browser to <a href="http://projects.statesman.com/happy-hours/">austin360.com/happyhours</a>. Enjoy, imbibe, and always, drink responsibly. If you have corrections or find a venue missing, <a href="submit.php">fill out this form</a> so we can get all the information. For general questions and suggestions, email <a href="mailto:happyhours@statesman.com">happyhours@statesman.com</a></p>
	</div>
</div>
