<div class="clearfix" id="ads">
	<div class="visible-xs hidden-sm hidden-md hidden-lg col-xs-12">
		<!-- www.austin360.com-wired/entertainment/bars -->
		<div id='div-gpt-ad-1388785723747-2' style='width:320px; height:50px;' class="center-block">
		<script type='text/javascript'>googletag.cmd.push(function() { googletag.display('div-gpt-ad-1388785723747-2'); });</script>
		</div>
	</div>
	<div class="hidden-xs visible-sm visible-md visible-lg col-xs-12">
		<!-- www.austin360.com-wired/entertainment/bars -->
		<div id='div-gpt-ad-1388785723747-1' style='width:728px; height:90px;' class="center-block">
		<script type='text/javascript'>googletag.cmd.push(function() { googletag.display('div-gpt-ad-1388785723747-1'); });</script>
		</div>
	</div>
</div>
